[WIP] Add git clone only branch
AuroraEditor/AuroraEditor pull request #186
Opened 2022-09-08 20:47 UTC by Angelk90

# Description

# Checklist

- [ ] I read and understood the [contributing guide](https://github.com/AuroraEditor/AuroraEditor/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/AuroraEditor/AuroraEditor/blob/main/CODE_OF_CONDUCT.md)
- [ ] My changes generate no new warnings
- [ ] My code builds and runs on my machine
- [ ] I documented my code
- [ ] Review requested

# Screenshots

https://user-images.githubusercontent.com/20476002/189222571-16b5d1bb-3a84-421d-a79f-426a6b0e46b7.mov

2022-09-08 22:01 UTC, nanashili commented
Don't put remote code in the branches file, i created a remote file specifically for remotes

2022-09-10 11:27 UTC, wdg commented
is this still a WIP?

2022-09-16 11:23 UTC, wdg commented on AuroraEditor/Base/Git/UI/Clone/GitCloneView.swift
> +                            errorView
```suggestion
```

(remove this)

2022-09-16 11:24 UTC, wdg commented on AuroraEditor/Base/Git/UI/Clone/GitCloneView.swift
> +                Log.info("Error: getRemoteBranch")
```suggestion
                Log.error("Error: getRemoteBranch")
```

2022-09-18 08:22 UTC, nanashili commented
This PR is starting to take to long with no actuve work really being done on it. Can you get this done @Angelk90 or we need to close it and open it at a later date.

2022-09-18 12:37 UTC, wdg requested changes

2022-09-18 12:37 UTC, wdg commented on AuroraEditor/Base/Git/UI/Clone/GitCloneView.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
```suggestion
            DispatchQueue.global(qos: .background).async {
```

2022-09-18 12:37 UTC, wdg commented on AuroraEditor/Base/Git/UI/Clone/GitCloneView.swift
> +                }
```suggestion
                if check == 2 {
                    DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
                      check = 0
                      activeSheet = .select
                    }
                }
```

2022-09-18 18:00 UTC, nanashili approved these changes

2022-09-18 18:24 UTC, wdg approved these changes

2022-09-18 18:24 UTC, merged