Feature: Add support for repository rules
AuroraEditor/AuroraEditor pull request #744
Opened 2024-07-21 18:27 UTC by nanashili

## Summary

This PR introduces GitHub Repository rules management within the editor.

## Changes Made

### Branch Creation

**Branch Name Restrictions**  
Specific branch names may be disallowed according to repository rules. If you attempt to create a branch with a restricted name, an error message will be displayed, preventing the creation of the branch.

### Metadata Rules

**Enforcing Metadata Standards**  
GitHub Enterprise Cloud users can now enforce metadata rules to ensure that specific fields conform to predefined values. For example, commit messages can be required to match a specific string or a regex pattern, ensuring consistency and adherence to project standards.

### Bypassing Rules

**Administrative Bypass Permissions**  
Administrators have the ability to grant certain apps, roles, or teams permission to bypass rulesets. When bypassing is permitted, the system will display warnings instead of errors, advising users to exercise caution when performing actions that would otherwise be restricted.

## TODO

- [ ] Finalize and test the branch name restriction logic.
- [ ] Conduct thorough testing to ensure all features work as intended.

## Motivation

The primary goal of this PR is to enhance repository management by introducing branch name restrictions, enforcing metadata rules, and allowing administrators to manage bypass permissions.

## Testing

- Verified that branch name restrictions trigger the appropriate error messages when attempting to create restricted branches.
- Tested the metadata rules enforcement to ensure commit messages conform to specified patterns.
- Confirmed that administrators can successfully manage bypass permissions and that the system displays warnings instead of errors when rules are bypassed.
- Conducted unit tests and integration tests to ensure all new features are functioning correctly.

## Screenshots/GIFs

None

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.

## Related Issues

This PR addresses the following issue(s): N/A

## Additional Notes

N/A

2024-07-21 18:28 UTC, aurora-care-bear commented
Thanks for submitting a pull request!
We will review it as soon as possible.

2024-07-23 20:46 UTC, 0xWDG requested changes

2024-07-23 20:46 UTC, 0xWDG commented on AuroraEditor/Features/Version Control/Model/Rules/Branch/RepoBranchRules.swift
> +                    print("No relevant rules for this branch name")
If not temporarily then please make this an NSLog / Logger.

2024-07-23 20:46 UTC, 0xWDG commented on AuroraEditor/Features/Version Control/Model/Rules/Branch/RepoBranchRules.swift
> +                    print("No relevant rules for this branch name")
Maybe it's better to remove the exception for the version control folder to have same code style anywhere, this could have been caught by swiftlint.

2024-07-24 22:34 UTC, 0xWDG approved these changes

2024-07-24 22:35 UTC, merged

2024-07-24 22:35 UTC, aurora-care-bear commented
Hey @nanashili,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.